name: Rust Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rust-analyzer

      - name: Build
        run: |
          cd rust
          cargo build --release -p multilspy-cli

      - name: Run CLI help
        run: |
          cd rust
          ./target/release/ra-lsp -h

      - name: Run CLI Command
        run: |
          cd rust
          $(pwd)/target/release/ra-lsp -w $(pwd)/multilspy-rust/test-rust-project -i $(pwd)/multilspy-rust/ra_initialize_params.json outgoing-calls-recursive --uri file://$(pwd)/multilspy-rust/test-rust-project/src/main.rs --line 34 --character 3 --max-depth 4
