name: Rust Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rust-analyzer

      - name: Cargo test
        run: |
          cd rust && cargo test
